# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recipe_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recipe_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13recipe_search.proto\x12\x06recipe\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"\x9d\x01\n\x06Recipe\x12\r\n\x05title\x18\x01 \x01(\t\x12\x14\n\x0cinstructions\x18\x02 \x01(\t\x12\x13\n\x0bingredients\x18\x03 \x03(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\x12\x12\n\ncategories\x18\x05 \x03(\t\x12\r\n\x05\x64iets\x18\x06 \x03(\t\x12\x0c\n\x04\x61rea\x18\x07 \x01(\t\x12\r\n\x05score\x18\x08 \x01(\x01\x12\x0b\n\x03img\x18\t \x01(\t\"1\n\x0eSearchResponse\x12\x1f\n\x07results\x18\x01 \x03(\x0b\x32\x0e.recipe.Recipe2G\n\x0cRecipeSearch\x12\x37\n\x06Search\x12\x15.recipe.SearchRequest\x1a\x16.recipe.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recipe_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=31
  _globals['_SEARCHREQUEST']._serialized_end=76
  _globals['_RECIPE']._serialized_start=79
  _globals['_RECIPE']._serialized_end=236
  _globals['_SEARCHRESPONSE']._serialized_start=238
  _globals['_SEARCHRESPONSE']._serialized_end=287
  _globals['_RECIPESEARCH']._serialized_start=289
  _globals['_RECIPESEARCH']._serialized_end=360
# @@protoc_insertion_point(module_scope)
